version: '3'

networks:
  test-network:
    driver: bridge

services:
  tests:
    build:
      context: .
      dockerfile: ./test.Dockerfile
    depends_on:
      - db
    networks:
      - test-network
    volumes:
      - ./reports:/go/src/app/reports
  db:
    image: mongo:4.4.0-rc11-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.test.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: switchboard
    restart: on-failure
    networks:
      - test-network
