name: Test

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests in Docker
      run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit --build

    - name: Cleanup containers
      run: docker-compose -f docker-compose.test.yml down --volumes

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./reports/coverage.txt
